version: '3.8'

services:

  site:
    image: ghcr.io/eesoymilk/future-xplorer:main
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: future-xplorer
    volumes:
      - future-xplorer-data:/data/db
    command: mongod
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  future-xplorer-data: