version: '3.8'

services:

  site:
    image: ${IMAGE_NAME}
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    ports:
      - "3000:3000"
    environment:
      NUXT_MONGO_USER: ${MONGO_USER}
      NUXT_MONGO_PASSWORD: ${MONGO_PASSWORD}
      NUXT_MONGO_HOST: mongo
      NUXT_MONGO_PORT: 27017
      NUXT_MONGO_DB: ${MONGO_DB}

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - future-xplorer-data:/data/db
    command: mongod
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/${MONGO_DB} --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  future-xplorer-data: