import { Base } from '@/types/base';

export interface Keyword extends Base {
  body: string;
  isAutoGenerated: boolean;
  caseId: string;
}

export interface Case extends Base {
  title: string;
  background: string;
  method: string;
  goal: string;
  challenge: string;
  result: string;
  reference: string;
  imageId?: string;
  other: string;

  keywords?: Keyword[];
}
