import { Base } from '@/types/base';

export interface NewKeyword {
  body: string;
}

export interface Keyword extends Base, NewKeyword {
  issueId: string;
  caseId: string;
  isAutoGenerated: boolean;
  category?: string;
}
